trigger:
  batch: false
  branches:
    include:
      - "*"

pr: none

variables:
- group: Release Management Resources
- group: Wildcard Cert Variables v2

pool:
  name: DAS - Continuous Integration

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.2.15
    endpoint: GitHub (SFA)
  - repository: self
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.2.4
    endpoint: GitHub (SFA) 

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  pool:
    name: DAS - Continuous Deployment
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/WireMockServiceApiArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/WireMockServiceApiArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        SharedStorageAccountConnectionString: $(SharedStorageAccountConnectionString)

  - template: pipeline-templates/job/api-deploy.yml
    parameters:
      DeploymentName: Deploy_WireMockServiceAPI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/WireMockServiceApiArtifacts/SFA.DAS.WireMockServiceApi.zip

  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentName: Deploy_WireMockServiceUI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/WireMockServiceApiArtifacts/SFA.DAS.WireMockServiceWeb.zip

- stage: Deploy_TEST2
  dependsOn: Build
  displayName: Deploy to TEST2
  pool:
    name: DAS - Continuous Deployment
  variables:
  - group: DevTest Management Resources
  - group: TEST2 DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/WireMockServiceApiArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/WireMockServiceApiArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        SharedStorageAccountConnectionString: $(SharedStorageAccountConnectionString)

  - template: pipeline-templates/job/api-deploy.yml
    parameters:
      DeploymentName: Deploy_WireMockServiceAPI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/WireMockServiceApiArtifacts/SFA.DAS.WireMockServiceApi.zip

  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentName: Deploy_WireMockServiceUI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/WireMockServiceApiArtifacts/SFA.DAS.WireMockServiceWeb.zip