trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

workspace:
  clean: all

variables:
- name: SolutionBaseName
  value: '__SolutionBaseName__'
- name: BuildPlatform
  value : 'any cpu'
- name: BuildConfiguration
  value: 'release'
- group: Release Management Resources
- group: Wildcard Cert Variables v2

pool:
  name: 'DAS - Continuous Integration'

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: 'GitHub (SFA)'

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- stage: Deploy_AT
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
  displayName: Deploy to AT
  pool:
    name: DAS - Continuous Deployment
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  jobs:
  - template: azure-pipelines-templates/deploy/job/arm-deploy.yml@das-platform-building-blocks
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/WireMockServiceAPIArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/WireMockServiceAPIArtifacts/azure/template.parameters.json
      ConfigSchemaPath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-apim-endpoints
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)

  - template: pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_WireMockServiceAPI
      DeploymentCondition: and(succeeded(), eq(${{ parameters.FindApprenticeshipTraining }}, true))
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppServiceName: $(FindApprenticeshipOuterApiAppServiceName)
      #DeploymentPackagePath: $(Pipeline.Workspace)/WireMockServiceAPIArtifacts/SFA.DAS.FindApprenticeshipTraining.Api.zip
      ApimResourceGroup: $(ApimResourceGroup)
      ApimInstanceName: $(InstanceName)
      AppServiceResourceGroup: $(ResourceGroupName)
      ApiVersionSetName: $(FindApprenticeshipOuterApiVersionSetName)
      ApiPath: $(FindApprenticeshipOuterApiPath)
      ApiBaseUrl: $(FindApprenticeshipOuterApiBaseUrl)
      ProductId: $(FindApprenticeshipProductId)
      ApplicationIdentifierUri: $(FindApprenticeshipOuterApiIdentifierUri)