trigger:
  batch: false
  branches:
    include:
      - "main"

variables:
- group: Release Management Resources
- group: Wildcard Cert Variables v2

pool:
  name: DAS - Continuous Integration

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.0
    endpoint: SkillsFundingAgency
  - repository: self
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.4
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  pool:
    name: DAS - Continuous Deployment Agents
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/ApiStubArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ApiStubArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        SharedStorageAccountConnectionString: $(SharedStorageAccountConnectionString)

  - template: pipeline-templates/job/api-deploy.yml
    parameters:
      DeploymentName: Deploy_StubAPI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ApiStubArtifacts/SFA.DAS.WireMockServiceApi.zip

  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentName: Deploy_StubUI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ApiStubArtifacts/SFA.DAS.WireMockServiceWeb.zip

  - template: pipeline-templates/job/post-deploy.yml

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  pool:
    name: DAS - Continuous Deployment Agents
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/ApiStubArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ApiStubArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        SharedStorageAccountConnectionString: $(SharedStorageAccountConnectionString)

  - template: pipeline-templates/job/api-deploy.yml
    parameters:
      DeploymentName: Deploy_StubAPI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ApiStubArtifacts/SFA.DAS.WireMockServiceApi.zip

  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentName: Deploy_StubUI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ApiStubArtifacts/SFA.DAS.WireMockServiceWeb.zip

  - template: pipeline-templates/job/post-deploy.yml
    
- stage: Deploy_TEST2
  dependsOn: Build
  displayName: Deploy to TEST2
  pool:
    name: DAS - Continuous Deployment Agents
  variables:
  - group: DevTest Management Resources
  - group: TEST2 DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/ApiStubArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ApiStubArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        SharedStorageAccountConnectionString: $(SharedStorageAccountConnectionString)

  - template: pipeline-templates/job/api-deploy.yml
    parameters:
      DeploymentName: Deploy_StubAPI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ApiStubArtifacts/SFA.DAS.WireMockServiceApi.zip

  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentName: Deploy_StubUI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ApiStubArtifacts/SFA.DAS.WireMockServiceWeb.zip

  - template: pipeline-templates/job/post-deploy.yml

- stage: Deploy_PP
  dependsOn: Build
  displayName: Deploy to PP
  pool:
    name: DAS - Continuous Deployment Agents
  variables:
  - group: PreProd Management Resources
  - group: PreProd Shared Resources
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DIG-PreProd-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/ApiStubArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ApiStubArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        SharedStorageAccountConnectionString: $(SharedStorageAccountConnectionString)
        
  - template: pipeline-templates/job/api-deploy.yml
    parameters:
      DeploymentName: Deploy_StubAPI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DIG-PreProd-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ApiStubArtifacts/SFA.DAS.WireMockServiceApi.zip

  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentName: Deploy_StubUI
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DIG-PreProd-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ApiStubArtifacts/SFA.DAS.WireMockServiceWeb.zip

  - template: pipeline-templates/job/post-deploy.yml
