trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
- group: Release Management Resources
- group: Wildcard Cert Variables v2

pool:
  name: 'DAS - Continuous Integration'

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: GitHub (SFA)
  repositories:
  - repository: self
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.2.4
    endpoint: GitHub (SFA) 

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/WireMockServiceApiArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/WireMockServiceApiArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)

  - template: pipeline-templates/job/deploy-api.yml
    parameters:
      DeploymentName: Deploy_WireMockServiceAPI      
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      AppServiceName: $(FindApprenticeshipOuterApiAppServiceName)
      DeploymentPackagePath: $(Pipeline.Workspace)/WireMockServiceApiArtifacts/SFA.DAS.RestApiStub.Api.zip