parameters:
  ServiceConnection: ''
  SubscriptionId: ''
  Location: ''
  Environment: ''
  TemplatePath: ''
  ParametersPath: ''
  TemplateSecrets: {}

jobs:
- deployment: DeployInfrastructure
  pool:
    name: DAS - Continuous Deployment
  environment: ${{ parameters.Environment }}
  workspace:
    clean: all
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../step/arm-deploy.yml
          parameters:
            Location: ${{ parameters.Location }}
            ParametersPath: ${{ parameters.ParametersPath }}
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: ${{ parameters.SubscriptionId }}
            TemplatePath: ${{ parameters.TemplatePath }}
            TemplateSecrets: ${{ parameters.TemplateSecrets }}
