parameters:
  DeploymentName:
  DeploymentApprovals:
  ServiceConnection:
  DeploymentPackagePath:

jobs:
- deployment: ${{ parameters.DeploymentName }}
  pool:
    name: DAS - Continuous Deployment Agents
  dependsOn: DeployInfrastructure
  variables:
    ResourceGroupName: $[dependencies.DeployInfrastructure.outputs['DeployInfrastructure.ArmOutputs.ResourceGroupName']]
    UiAppServiceName: $[dependencies.DeployInfrastructure.outputs['DeployInfrastructure.ArmOutputs.UiAppServiceName']]
  environment: ${{ parameters.DeploymentApprovals }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: $(UiAppServiceName)
            DeploymentPackagePath: ${{ parameters.DeploymentPackagePath }}